/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualiseRouteImport } from './routes/visualise'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MixRouteImport } from './routes/mix'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as InspireRouteImport } from './routes/inspire'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityIdRouteImport } from './routes/community.$id'

const VisualiseRoute = VisualiseRouteImport.update({
  id: '/visualise',
  path: '/visualise',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MixRoute = MixRouteImport.update({
  id: '/mix',
  path: '/mix',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const InspireRoute = InspireRouteImport.update({
  id: '/inspire',
  path: '/inspire',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/inspire': typeof InspireRoute
  '/library': typeof LibraryRoute
  '/mix': typeof MixRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/visualise': typeof VisualiseRoute
  '/community/$id': typeof CommunityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/inspire': typeof InspireRoute
  '/library': typeof LibraryRoute
  '/mix': typeof MixRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/visualise': typeof VisualiseRoute
  '/community/$id': typeof CommunityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRouteWithChildren
  '/inspire': typeof InspireRoute
  '/library': typeof LibraryRoute
  '/mix': typeof MixRoute
  '/profile': typeof ProfileRoute
  '/share': typeof ShareRoute
  '/visualise': typeof VisualiseRoute
  '/community/$id': typeof CommunityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/community'
    | '/inspire'
    | '/library'
    | '/mix'
    | '/profile'
    | '/share'
    | '/visualise'
    | '/community/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/community'
    | '/inspire'
    | '/library'
    | '/mix'
    | '/profile'
    | '/share'
    | '/visualise'
    | '/community/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/community'
    | '/inspire'
    | '/library'
    | '/mix'
    | '/profile'
    | '/share'
    | '/visualise'
    | '/community/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  InspireRoute: typeof InspireRoute
  LibraryRoute: typeof LibraryRoute
  MixRoute: typeof MixRoute
  ProfileRoute: typeof ProfileRoute
  ShareRoute: typeof ShareRoute
  VisualiseRoute: typeof VisualiseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visualise': {
      id: '/visualise'
      path: '/visualise'
      fullPath: '/visualise'
      preLoaderRoute: typeof VisualiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mix': {
      id: '/mix'
      path: '/mix'
      fullPath: '/mix'
      preLoaderRoute: typeof MixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspire': {
      id: '/inspire'
      path: '/inspire'
      fullPath: '/inspire'
      preLoaderRoute: typeof InspireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRouteWithChildren,
  InspireRoute: InspireRoute,
  LibraryRoute: LibraryRoute,
  MixRoute: MixRoute,
  ProfileRoute: ProfileRoute,
  ShareRoute: ShareRoute,
  VisualiseRoute: VisualiseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
